name: Email Service Sync CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - src/Services/EmailService/EmailService.Sync/**
      - src/BuildingBlocks/Infrastructure/**
      - .github/workflows/email-service-sync.yml
      - .github/workflows/build_common.yml
      - .github/workflows/deploy_function_app_common.yml
      - .github/workflows/appsettings/email-service-sync/**.json
  pull_request:
    branches: [ master ]
    paths:
      - src/Services/EmailService/EmailService.Sync/**
      - src/BuildingBlocks/Infrastructure/**
      - .github/workflows/email-service-sync.yml
      - .github/workflows/appsettings/email-service-sync/**.json
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment for CD'
        required: false
        default: 'dev' 
        options:
        - sand
        - dev
        - test
        - prod

jobs: 
  build:
    uses: ./.github/workflows/build_common.yml
    with:
      project_path: src/Services/EmailService
      project_name: EmailService.Sync
      appsettings_path: email-service-sync

  sand:
      if: ${{ github.event.inputs.environment == 'sand' }}
      needs: build
      uses: ./.github/workflows/deploy_function_app_common.yml
      with:
        azure_function_app_name: func-mm-email-service-sync-sand
        project_name: EmailService.Sync
        appsettings_json: email-service-sync/email-service-sync-sand.json
      secrets:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  dev:
      if: ${{ github.event_name == 'push' ||  github.event.inputs.environment == 'dev' }}
      needs: build
      uses: ./.github/workflows/deploy_function_app_common.yml
      with:
        azure_function_app_name: func-mm-email-service-sync-dev
        project_name: EmailService.Sync
        appsettings_json: email-service-sync/email-service-sync-dev.json
      secrets:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  test:
      if: ${{ github.event.inputs.environment == 'test' }}
      needs: build
      uses: ./.github/workflows/deploy_function_app_common.yml
      with:
        azure_function_app_name: func-mm-email-service-sync-test
        project_name: EmailService.Sync
        appsettings_json: email-service-sync/email-service-sync-test.json
      secrets:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  prod:
      if: ${{ github.event.inputs.environment == 'prod' }}
      needs: build
      uses: ./.github/workflows/deploy_function_app_common.yml
      with:
        azure_function_app_name: func-mm-email-service-sync-prod
        project_name: EmailService.Sync
        appsettings_json: email-service-sync/email-service-sync-prod.json
      secrets:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
